project:
  type: website

website:
  # favicon:
  title: "My Personal Blog"
  site-url: https://pipme.github.io
  repo-url: https://github.com/pipme/pipme.github.io
  repo-actions: [edit]
  description: "Personal Blog"
  open-graph: true
  navbar:
    title: false
    left:
      - href: index.qmd
        text: Home
      - href: gist.qmd
        text: Gist
      - href: ./tools/index.qmd
        text: Tool
    right:
      - href: about.qmd
        text: About
      - icon: card-list
        href: blog+gist.qmd
        text: All
        # text: "\u200B" # ZERO WIDTH SPACE, it seems causing non-alignment problem in Safari
      - icon: github
        href: https://github.com/pipme
      - icon: rss
        menu:
          - href: index.xml
            text: blog
          - href: blog+gist.xml
            text: blog+gist
  google-analytics: "G-K0VMSWF7B9"
  cookie-consent: true
  comments:
    giscus:
      repo: pipme/pipme.github.io
      repo-id: R_kgDOJtreTA
      category: Announcements
      category-id: DIC_kwDOJtreTM4CXLJm
      mapping: pathname
      loading: lazy
      # dark theme issue will be fixed in quarto 1.4
  page-footer:
    center:
      - text: "{{< ai google-scholar >}}"
        href: https://scholar.google.com/citations?user=9mu6FKcAAAAJ&hl=en
      - text: "{{< fa brands linkedin-in >}}"
        href: https://www.linkedin.com/in/chengkun-li-62360612b/
      - text: "{{< fa brands github >}}"
        href: https://github.com/pipme
      - text: "{{< fa brands 500px >}}"
        href: https://500px.com/p/sjtulck
      - text: "{{< fa envelope >}}"
        href: "mailto:sjtulck@gmail.com"
format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
