---
title: "Start Blogging with Quarto"
date: "2023-06-10"
date-modified: last-modified
categories: [news]
bibliography: [../all.bib, local.bib]
format:
  html: default
---

Quarto seems to be a great choice for posting with executable codes and it's nice that one can generate pdfs, slides etc. from a quasi-markdown file with unified styles (qmd). So I decide to start blogging with Quarto and probably make slides with it in the future as the web-based solution (revealjs) looks elegant and promising in the long run.

Building a site with Quarto is relatively easy and interesting. The documentation is very nicely written. You could find some useful tips [here](../2023-06-11-Quarto-tips/index-gist.qmd). See @navarro2022 for more workthrough details.  

By the way, I fell in love with writing in markdown since the birth of another great tool [Obsidian](https://obsidian.md/) and gradually realize that habitual writing is essential for a researcher, for building one's second brain, undertanding things better and sharing knowledge.

For Obsidian, I put some useful plugins [here](../2023-06-11-Obsidian-Zotero-tips/), together with Zotero's. Maybe I could write a blog for sharing my workflows in an academic life. I will probably wait until I get more familiar with Quarto and see how they fit with daily needs.

Welcome to my blog 😃!


