---
title: "BibTeX and natbib: Zotero arXiv article entry fix"
date: "2025-10-31"
date-modified: last-modified
categories: [BibTeX, Zotero, LaTeX, Better BibTeX]
format:
  html: default
---

When exporting references from Zotero to BibTeX (using Better BibTeX), arXiv articles may not be formatted correctly in LaTeX-generated PDFs, as BibTeX [is by default unaware of arXiv/preprint type](https://tex.stackexchange.com/a/429140). For example, currently (2025) an arXiv article entry from Zotero would look like this:[^1]

```bibtex
@misc{betancourtConceptualIntroductionHamiltonian2018,
  title = {A Conceptual Introduction to {{Hamiltonian Monte Carlo}}},
  author = {Betancourt, Michael},
  year = 2018,
  month = jul,
  number = {arXiv:1701.02434},
  eprint = {1701.02434},
  primaryclass = {stat},
  publisher = {arXiv},
  doi = {10.48550/arXiv.1701.02434},
  archiveprefix = {arXiv},
}
```

The above would appear in the references section as:

```
Michael Betancourt. A conceptual introduction to Hamiltonian Monte Carlo,
July 2018.
```

A simple fix is to add a `note` field in the BibTeX entry with the arXiv identifier `arXiv:1701.02434`, so that the reference would look like:

```
Michael Betancourt. A conceptual introduction to Hamiltonian Monte Carlo,
July 2018. arXiv:1701.02434.
```

This can be automated by adding a postscript to the Better BibTeX export preferences in Zotero:

```javascript
if (Translator.BetterTeX) {
  if (zotero.itemType == "preprint") {
  var arxivID = zotero.number;
  // Zotero.debug(JSON.stringify(arxivID))
  // Zotero.debug(JSON.stringify(zotero))
  tex.add({ name: 'note', value: arxivID});
  }
}
```

I hadn’t noticed this issue with arXiv articles before, as I usually relied on journal or conference templates that handled them correctly. When templates are unavailable, it might be preferable to switch to BibLaTeX instead of BibTeX + natbib, which provides more robust handling of preprint and arXiv entries.

[^1]: Previously, these entries were exported as `@article` types in Zotero, but they now default to `@misc` types.